# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: CIRG
name: CIRG
description: >
  The Computational Intelligence Research Group (CIRG) home page at the [Department of Information Technology](http://www.it.nuigalway.ie), [National University of Ireland, Galway](http://www.nuigalway.ie).
footer_text: National University of Ireland Galway

url: https://nuig.github.io
baseurl:
last_updated: # leave blank if you don't want to display last updated
google_analytics: UA-120208085-1

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  research:
    output: true
    permalink: /research/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & Excludes
include: ['_pages']
exclude: ['deploy','.fuse*']

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:
  style: apa
  locale: en

  sort_by: year, month, timestamp
  order: descending, descending, descending

  source: /_bibliography/
  bibliography: autogen_all.bib
  bibliography_template: bib
  repository: data

  # <li> for each entry will be handled by bib.html
  # we wrap them with <div class='delete-li'>
  bibliography_item_tag: 'div'
  bibliography_item_attributes: {'class': 'delete-li'}

  replace_strings: true
  join_strings: true

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "3.3.1"
datatables_version: "1.10.16"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
